# Configuration for Alacritty, the GPU enhanced terminal emulator.

import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]
live_config_reload = true

[window]
  opacity = 1.0

[window.padding]
  x = 4
  y = 4

[font]
  size = 11.0

[font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

[font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

[font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  # Bold italic font face
  #bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    #family: monospace

    # The `style` can be specified to pick a specific face.
    #style: Bold Italic

[font.offset]
   x = 0
   y = 0

[font.glyph_offset]
   x = 0
   y = 0

[shell]
  program = "/bin/zsh"
